### ISSUE TITLE
Put scripts into containers?

### ISSUE THREAD

**Issue by willirath** [geomar-od/rasmus-cmems-downloads#13]
I'm not really sure if we should put the scripts into the containers or not.

@kathoef: You probably have some more solid insight on this?

**Comment by kathoef** [comment]
This depends on the exact use case, I would say. Here, it seems the goal is to have something like a "standalone application", i.e. run the container to get some data downloading and data conversion done. If the scripts are not provided with the containers, then it would be necessary to have them checked out (at worst manual?) on the machine, where everything is intended to happen, which would add unnecessary layers of complexity (especially from a version integrity perspective?) to the desired pipeline. But as an external wrapper script is necessary to operate that pipeline, one might also argue differently here.

**Comment by willirath** [comment]
OK, then I think we should put the scripts into the containers.

This also means we should restructure the repository to one directory per application.

**Comment by eshchekinova** [comment]
This is a bit unclear, does it mean that every time the application is run we create a new directory?  Am I right? What should be the naming format for directory?
