### ISSUE TITLE
Use Python for the download part as well?

### ISSUE THREAD

**Issue by willirath** [geomar-od/rasmus-cmems-downloads#3]
Handling the input arguments is much easier with Python (see https://github.com/eshchekinova/example-cmems-download-automation/blob/7b8f6704081f80ae8f32d9a168b7ae183959644d/NetCDF2CSVPhysModel.py#L6_L14). So we should consider also transforming the download part to Python.

The downside would be, that the `motuclient` does not provide a clean Python API. But there's two workarounds in https://github.com/clstoulouse/motu-client-python/issues/19:
- Use Python for building the call to the `motuclient` and pass it via, e.g., `os.system` or `subprocess.popen`. (See here: https://github.com/clstoulouse/motu-client-python/issues/19#issuecomment-566927150)
- Use the `optparse` module and directly (well...) call the Python interface. (See here: https://github.com/clstoulouse/motu-client-python/issues/19#issuecomment-733962916)

**Comment by eshchekinova** [comment]
All right,  I start to write download part in Python using os.system()  call. 

How to handle times and other arguments such as lat, long?

**Comment by willirath** [comment]
I think we should leave everything global for now (so just hard-code lat, lon, depth) in the script and only accept `start_time` and `end_time` (see also #6).

**Comment by eshchekinova** [comment]
All right.

**Comment by willirath** [comment]
This is done with #7, #8, and #11.

Closing.
