### ISSUE TITLE
Add Zarr conversion?

### ISSUE THREAD

**Issue by willirath** [geomar-od/rasmus-cmems-downloads#5]
NetCDF can be quite slow to handle especially if the data is split across many small files. For high-resolution datasets, I usually convert to [Zarr](https://zarr.readthedocs.io/en/stable/) for any active work on the data and only stick to netCDF for the long-term archive. So we should also add a netCDF --> Zarr conversion.

[Converting to zarr can be done with xarray.](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_zarr.html)

Later, the conversion to parquet (see #4) would probably also be easier based on Zarr.

**Comment by eshchekinova** [comment]
So, first step is NetCDF-> Zarr, then Zarr-> parquet ?

**Comment by willirath** [comment]
How big would a GLOBAL_ANALYSIS_FORECAST_PHY netCDF file be for a full year at one-hour resolution? `365 * 24 * 35 MB = 306 GB`? This would be too big for a direct conversion, I think.

**Comment by willirath** [comment]
Done with #7. Closing.
