### ISSUE TITLE
File naming and timestamps

### ISSUE THREAD

**Issue by willirath** [geomar-od/rasmus-cmems-downloads#6]
I think we should find a file naming convention with a start and end time. In the current examples, there's only one time step per file, but this won't be possible (or at least advisable) for the full dataset, because we would end up with more than 40.000 files if we store hourly data.

So we should go for something like 
```
{product_name}_{start_time}_{end_time}.{extension}
```
where
- `product_name` is either `GLOBAL_ANALYSIS_FORECAST_PHY` or `GLOBAL_ANALYSIS_FORECAST_WAV`
- `start_time` indicates the left (inclusive) boundary of the time interval covered and,
- `end_time` indicates the right (inclusive) boundary of the time interval that is covered.

If I understand the [docs of `motuclient`](https://github.com/clstoulouse/motu-client-python#options) correctly, we could just, e.g., specify
```python
start_date="2020-01-01"
end_date="2020-12-31"
```
and get all time steps that are later than `"2020-01-01T00:00:00"` and earlier than `"2021-01-01T00:00:00"`.

**Comment by willirath** [comment]
Then, we'd have `GLOBAL_ANALYSIS_FORECAST_PHY_2020-01-01_2020-12-31.nc` for a file that covers all time steps of the year 2020.

**Comment by eshchekinova** [comment]
Ok, you understand it right, it can be done with start and end of date. For wave model and for phys model there are different 
time stamps used. I guess, this two different time grids could be later interpolated to user-given times?

**Comment by willirath** [comment]
Yes, here, we should only handle the raw data as they are provided. Interpolation in time is very easy on the fly and will probably be done whenever the data is used later on.

**Comment by willirath** [comment]
- `{product_id}/nc/{product_id}_{variable_name}_{start_day}.nc`: daily files, separate files for each variable
- `{product_id}/{product_id}_{variable_name}_{start_day}_{end_day}.zarr/`: one large store for all files
- `{product_id}/pq/{product_id}_{variable_name}_{start_day}_{end_day}.pq`: one or more parquet files
- Time intervals as `[start_day, end_day]`

examples:
- `global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh/nc/global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh_uo_2020-01-01.nc`
- `global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh/nc/global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh_vo_2020-01-01.nc`
- ...
- `global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh/global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh_uo_2020-01-01_2020-12-31.zarr/`
- `global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh/global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh_vo_2020-01-01_2020-12-31.zarr/`
- ...

**Comment by willirath** [comment]
Currently, [MotuClDownloadCMEMSPhysModel.py](https://github.com/eshchekinova/example-cmems-download-automation/blob/master/MotuClDownloadCMEMSPhysModel.py) and [MotuClDownloadCMEMSWavModel.py](https://github.com/eshchekinova/example-cmems-download-automation/blob/master/MotuClDownloadCMEMSWavModel.py) do not write daily files.

We should refactor them to download all data for the given time span (via `--time_min` and `--time_max` args) but split downloads into daily files following the naming convention above (`{product_id}/nc/{product_id}_{variable_name}_{start_day}.nc`).

**Comment by willirath** [comment]
In a separate step (after [the above comment](https://github.com/eshchekinova/example-cmems-download-automation/issues/6#issuecomment-780017845) has been addressed, we should add a check which only downloads existing files (see https://docs.python.org/3/library/pathlib.html for details on how to do this with `pathlib`). This functionality should get a command line flag (added via argparse) to switch to forcing re-downloads if wanted, but defaulting to skipping existing files as a default.

**Comment by willirath** [comment]
We should put the info from this issue into the README.

**Comment by willirath** [comment]
Closing here, as we've found and documented an agreement on naming.
